apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: esade-teaching
  region: eu-west-1
  version: "1.32"

managedNodeGroups:
  - name: students
    instanceType: t3a.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    amiFamily: AmazonLinux2023
    volumeSize: 20
    volumeType: gp3

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: metrics-server
    version: latest

cloudWatch:
  clusterLogging:
    enableTypes: []
